### PR TITLE
[WIP] Using Reactive.jl for Parameters and Discretes

### PR DESCRIPTION
**Pull request by tshort**
Still experimental. For #17.

### CODE REVIEW

**Comment by iraikov** [comment]
My only comment is perhaps you should consider a better name for push!. 'reinit' is clear about what it does, would it make sense to have reinitDiscrete or something like that?

**Comment by tshort** [comment]
Ivan, I didn't mean for this to be merged in, yet. The WIP in the title means "Work in Progress". This is still experimental. The WIP pull request is a way to preview what's coming and allow multiple folks to work on it. I think we'll need to merge in a few bug fixes to the 0.1.0 release before introducing the Reactive stuff.

**Comment by tshort** [comment]
Also, I think I reverted your pull request properly. I'll open a new WIP pull request from the reactive branch at some point.

**Comment by iraikov** [comment]
Oh ok, I was indeed wondering what WIP means :-) But I am curious to try
out the reactive stuff. Is there some way to merge the pull request in my
fork, or what's the correct workflow here?

**Comment by tshort** [comment]
You should be able to pull the reactive branch and work on that:

```
git pull origin reactive
```

That's also a good way to try out pull requests before accepting them. You should be able to push to that, too.

**Comment by iraikov** [comment]
Thanks, will try out the reactive branch with the neural models tonight.

**Pull request merged**
