### PR TITLE
First changes to support Julia v0.5

### PR DESCRIPTION
**Pull request by tshort**
Changes include:

* String changes
* Some duplicate method removal (many more still there)
* `collect(x)` instead of `[x]`
* Documentation syntax changes

### CODE REVIEW

**Comment by iraikov** [comment]
Tom, it's great to see you returning to Sims :-) I see that the neural examples are commented out in the julia-0.5 branch, can you briefly tell me what kind of problems you encountered, and I will work on fixing them. Thanks a lot!

**Comment by tshort** [comment]
Hi Ivan! It's a mix of issues. Some are pretty easy to spot. For example, newer Julia doesn't like `somefun (x)` with the space after the function name. I got to the point that it was just easier to comment tests out that didn't work. I'm also pretty sure the Grid.jl stuff is broken.

This is close to being mergable. I may even merge tonight. The tests that are not commented out pass, and most things work. I still think initialization with JuMP might be broken.

After I merge this, it'd be great if you could fix your parts.

After merging, there are some things that would be nice:

* Using anonymous functions that are now fast instead of the eval hack I used.
* Getting precompilation to work. It needs the item above.
* Better Plots.jl plotting.
* Update the API with regards to Reactive.

**Comment by iraikov** [comment]
Hi Tom,

   Ok, in that case I will wait for you to merge, and then I will update
the neural examples to conform to the 0.5 syntax. I haven't used Julia in a
while, it will be great if anonymous functions are fast.

  -Ivan

**Comment by tshort** [comment]
Shoot. I forgot to squash, and I missed the checkbox or whatever that allows me to do this on merging.

**Pull request merged**
