### PR TITLE
[DONT MERGE] Travis experimentation

### PR DESCRIPTION
**Pull request by tshort**
I'm trying to get travis building to work. There's other junk in here that should be pulled elsewhere.

### CODE REVIEW

**Comment by tshort** [comment]
This is irritating. I can't get gfortran to work right to compile dassl. I'm tempted to depreciate dassl. It's also a pain on windows. I'm not happy about that because I find dassl to be simpler and easier to fiddle with than sundials. Comments @iraikov?

**Comment by iraikov** [comment]
Actually, I also like dassl for its simplicity, and I think a bit better performance on problems with structural events. But why not just default to sundials if dassl cannot be compiled?

**Comment by tshort** [comment]
Sounds like a good approach...

**Comment by tshort** [comment]
The same gfortran errors noted are showing up in Ipopt, too:

https://github.com/JuliaOpt/Ipopt.jl/issues/23

**Comment by tkelman** [comment]
You can fix the gfortran problem while keeping `language: julia` if you like by adding a line `rm -f ~/julia/lib/julia/libgfortran.so.3`. We should have this fixed for our next point release, it required building our own gcc for use on the buildbot that compiles the generic linux binaries.

**Comment by tkelman** [comment]
No guarantees it'll work, but you might also want to try @nolta's Fortran-to-Julia converter on dassl. See pass0.sh and pass1.jl here: https://github.com/nolta/SpecialFunctions.jl/tree/master/src/amos

**Comment by tshort** [comment]
Cool @tkelman! I'll have to try @nolta's converter. Thanks also for your input on `language: julia`. It looked like a fix was in the works.

**Comment by tkelman** [comment]
Fixing https://github.com/JuliaLang/BinDeps.jl/issues/123 should hopefully help make this kind of thing easier to debug in the future.

**Pull request closed without merging**
