### PR TITLE
Mkdocs candidate

### PR DESCRIPTION
**Pull request by tshort**
The documentation structure is pretty well set now. I like the way it works. Lots of changes here:

* Code now has inline documentation for all user code and models
  using Docile. Should work with Julia 0.4 with some tweaks.

* Reorganize lib into a top-level directory and put it in a Sims.Lib
  module.

* Reorganize docs and examples into top-level directories.

* Included examples in a Sims.Examples module with the following modules.
  * Sims.Examples.Basics
  * Sims.Examples.Lib
  * Sims.Examples.Neural

* Removed all plotting and simulation commands from examples.

* Added a `runexamples` function in each of the examples modules.

* Added a script to build the docs. The contents of the following
  directories are automatically generated:
    docs/api
    docs/lib
    docs/examples

* Added documentation on plotting results.

* Removed the /doc folder and added a /docs Mkdocs documentation folder.

* Added an mkdocs.yml folder and a docs/css/github.css file for
  syntax highlighting.

### CODE REVIEW

**Comment by tshort** [comment]
For issue #10.

**Comment by tshort** [comment]
@iraikov, if you want to add docs to more of your your neural examples and include them in Sims.Examples.Neural, please do. Let me know if you have questions on the format. Hopefully, you can just copy what I did in other places.

I'd like to tag a release soon, so let me know if there's anything you'd like to do before we tag a release.

**Comment by iraikov** [comment]
Hi Tom,

    I am currently trying to figure out if I can use InitialEquation to
initialize states and parameters when a structural event occurs.
So let me see if I can improve the initial equation functionality a little
bit before you tag the release. Thanks,

   Ivan

**Comment by tshort** [comment]
Ok. That functionality is likely to be weak. Let me know how it goes.

**Pull request merged**
